"""Pin the installed Windows/Python 3.12 runtime and developer dependency closures.

Run with .venv/Scripts/python.exe. This does not ask an index to resolve versions,
change the source environment, or include the optional model/GPU dependencies.
The generated files are version locks, not wheel-hash or build-tool locks.
"""

from __future__ import annotations

import hashlib
import json
import platform
import sys
import tomllib
from collections import deque
from importlib import metadata
from pathlib import Path

from packaging.markers import default_environment
from packaging.requirements import Requirement
from packaging.specifiers import SpecifierSet
from packaging.utils import canonicalize_name
from packaging.version import Version

ROOT = Path(__file__).resolve().parents[1]
CORE_NAMES = frozenset({"pandas", "streamlit", "plotly"})
DEV_NAMES = frozenset({"pytest", "ruff", "openpyxl", "requests"})


def closure(roots: list[str]) -> dict[str, str]:
    """Resolve only already-installed metadata, respecting Windows and extras markers."""
    environment = default_environment()
    pending = deque(Requirement(text) for text in roots)
    versions: dict[str, str] = {}
    requested_extras: dict[str, set[str]] = {}
    expanded_contexts: dict[str, set[str]] = {}
    while pending:
        requirement = pending.popleft()
        name = canonicalize_name(requirement.name)
        if requirement.url is not None:
            raise RuntimeError(f"Cannot turn a direct URL dependency into an index version lock: {requirement}")
        try:
            distribution = metadata.distribution(name)
        except metadata.PackageNotFoundError as exc:
            raise RuntimeError(f"Required distribution is not installed in the source environment: {name}") from exc
        installed = distribution.version
        if requirement.specifier and Version(installed) not in requirement.specifier:
            raise RuntimeError(f"Installed {name}=={installed} does not satisfy {requirement}")
        requires_python = distribution.metadata.get("Requires-Python")
        if requires_python and Version(environment["python_full_version"]) not in SpecifierSet(requires_python):
            raise RuntimeError(f"Installed {name}=={installed} requires Python {requires_python}")
        versions[name] = installed
        extras = requested_extras.setdefault(name, set())
        extras.update(canonicalize_name(extra) for extra in requirement.extras)
        contexts = {"", *extras}
        unexpanded = contexts - expanded_contexts.setdefault(name, set())
        if not unexpanded:
            continue
        for text in distribution.requires or []:
            dependency = Requirement(text)
            if dependency.marker is None or any(
                dependency.marker.evaluate({**environment, "extra": extra}) for extra in unexpanded
            ):
                pending.append(dependency)
        expanded_contexts[name].update(unexpanded)
    return dict(sorted(versions.items()))


def requirements_from_project() -> tuple[list[str], list[str]]:
    project = tomllib.loads((ROOT / "pyproject.toml").read_text("utf-8"))["project"]
    runtime = project["dependencies"]
    developer = project["optional-dependencies"]["dev"]
    if {canonicalize_name(Requirement(item).name) for item in runtime} != CORE_NAMES:
        raise RuntimeError("Runtime roots changed; review CORE_NAMES before regenerating these locks.")
    if {canonicalize_name(Requirement(item).name) for item in developer} != DEV_NAMES:
        raise RuntimeError("Developer roots changed; review DEV_NAMES before regenerating these locks.")
    environment = {**default_environment(), "extra": ""}
    for text in [*runtime, *developer]:
        requirement = Requirement(text)
        if requirement.marker and not requirement.marker.evaluate(environment):
            raise RuntimeError(f"A declared root is inactive on this machine; review it explicitly: {requirement}")
    return runtime, developer


def write_lock(filename: str, roots: list[str], packages: dict[str, str]) -> dict:
    header = [
        "# Generated by scripts/lock_dependencies.py from installed distribution metadata.",
        "# Target: CPython 3.12, Windows x64. Not a Linux/macOS or GPU lock.",
        "# Exact runtime/developer versions only; build tools and wheel hashes are not locked.",
        "# Install with: python -m pip install -r " + filename,
        "# Roots: " + "; ".join(roots),
        "",
    ]
    text = "\n".join([*header, *(f"{name}=={version}" for name, version in packages.items()), ""])
    path = ROOT / filename
    path.write_text(text, encoding="utf-8", newline="\n")
    return {"path": filename, "packages": len(packages), "sha256": hashlib.sha256(path.read_bytes()).hexdigest()}


def main() -> None:
    expected_prefix = (ROOT / ".venv").resolve()
    if Path(sys.prefix).resolve() != expected_prefix:
        raise SystemExit("Use this project's .venv/Scripts/python.exe to read its installed metadata.")
    if sys.platform != "win32" or sys.version_info[:2] != (3, 12) or platform.machine().lower() not in {"amd64", "x86_64"}:
        raise SystemExit("These locks must be generated on Windows x64 with CPython 3.12.")
    runtime, developer = requirements_from_project()
    runtime_packages = closure(runtime)
    developer_packages = closure([*runtime, *developer])
    if any(name.startswith("nvidia-") for name in developer_packages) or {"torch", "transformers", "accelerate"} & developer_packages.keys():
        raise RuntimeError("Unexpected GPU/model dependency in the runtime/developer closure.")
    results = [
        write_lock("requirements-windows.lock", runtime, runtime_packages),
        write_lock("requirements-dev-windows.lock", [*runtime, *developer], developer_packages),
    ]
    print(json.dumps({"source_prefix": sys.prefix, "python": platform.python_version(), "locks": results}, indent=2))


if __name__ == "__main__":
    main()
